language: rust
rust:
  - nightly
#
#before_script:
#- rustup target add i686-unknown-linux-gnu
# TODO: renable this once https://github.com/rust-lang/rust/issues/49033 is fixed.
#
os:
  - linux
addons:
  apt:
    sources:
    - sourceline: ppa:hvr/z3
    packages:
    - libz3-dev
script:
  - cargo build
  - cargo test
  - cargo doc
