# Xargo.toml

[dependencies]
std = {features = ["panic_unwind", "jemalloc"]}

[target.x86_64-unknown-linux-gnu.dependencies.term]
stage=1

[target.x86_64-unknown-linux-gnu.dependencies.proc_macro]
stage=2